resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=debug

generatorOptions:
  disableNameSuffixHash: true
